### PR TITLE
Allow editor configurations

### PR DESCRIPTION
**Pull request by sarahchen6**
This PR adds a `.editorconfig` file to to support editor configurations.

### CODE REVIEW

**Review by delner — COMMENTED** [review]
Is this for your local dev environment? Or is this meant to be a dev standard?

**Comment by sarahchen6** [comment]
> Is this for your local dev environment? Or is this meant to be a dev standard?

@delner The `.editorconfig` file would be a dev standard for this repository.

**Review by lloeki — APPROVED** [review]
Very useful, thanks!

**Comment by lloeki** [comment]
@delner This file allows defining a small set of consistent rules across editors by auto-configuring them, see https://editorconfig.org/

Some editors support it natively, others need an extension or plugin to make use of it, e.g:

- https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
- https://github.com/editorconfig/editorconfig-vim

**Pull request merged**
